version: "3.9"
services:

  web: 
    build: 
      context: .
      dockerfile: Codetrics/Dockerfile
    ports:
      - "8000:3000"
  
  test:
   build:
    context: .
    dockerfile: RunEnvironment/Dockerfile
   ports:
    - "8080:80"
